#连接数据库
spring:
  datasource:
     druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 3
      min-idle: 3
      max-active: 30
      max-wait: 1500
      validationQuery: SELECT 'x'      a    
      #监控的配置
      stat-view-servlet:
        login-username: system
        login-password: 123456
        allow: 
        deny: 
        url-pattern: /druid/*
        enabled: true
        
      
